#! /bin/bash
#
# launch
# Copyright (C) 2021 Mark Wells <mwellsa@gmail.com>
#
# Distributed under terms of the MIT license.
#

MONITORS=( $(xrandr --listmonitors | rev | cut -d' ' -f1 | rev | sort) )
# Take output that looks like
# Monitors: 4
#  0: +*eDP-1-1 1920/344x1080/194+5760+0  eDP-1-1
#  1: +HDMI-0 1920/476x1080/268+0+0  HDMI-0
#  2: +DP-2 1920/476x1080/268+3840+0  DP-2
#  3: +DP-6 1920/476x1080/268+1920+0  DP-6
# and convert it to
# "4 DP-2 DP-6 eDP-1-1 HDMI-0"
MONITORS="${MONITORS[@]}"

if [ "$MONITORS" == "4 DP-2 DP-6 eDP-1-1 HDMI-0" ]; then
    # 4 monitor setup
    #       eDP-1-1: laptop display
    #       DP-2: DisplayPort 1.3 over USB 3.1 Gen 2 Type-C
    #       DP-6: Mini DisplayPort
    #       HDMI-0: HDMI
    # see https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Multi-monitor
    # nvidia-settings --query CurrentMetaMode # remove everything before the ::
    nvidia-settings --assign CurrentMetaMode="\
        DPY-4: nvidia-auto-select @1920x1080 +0+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, \
        DPY-2: nvidia-auto-select @1920x1080 +3840+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, \
        DPY-7: nvidia-auto-select @1920x1080 +1920+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0, ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"

    xrandr \
        --output DP-0 --off \
        --output DP-1 --off \
        --output DP2 --mode 1920x1080 --pos 3840x0 --rotate normal \
        --output DP-3 --off \
        --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP-4 --off \
        --output DP-5 --off \
        --output DP-6 --mode 1920x1080 --pos 1920x0 --rotate normal \
        --output eDP-1-1 --primary --mode 1920x1080 --pos 5760x0 --rotate normal
else
    echo "No recognized configuration."
fi
