#! /bin/bash
#
# launch
# Copyright (C) 2021 Mark Wells <mwellsa@gmail.com>
#
# Distributed under terms of the MIT license.
#

MONITORS=( $(xrandr | grep [[:space:]]connected | cut -d' ' -f1 | sort) )
# Take output that looks like
#     $ xrandr | grep [[:space:]]connected
#     DP-2 connected (normal left inverted right x axis y axis)
#     HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 476mm x 268mm
#     DP-6 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 476mm x 268mm
#     eDP-1-1 connected primary 1920x1080+5760+0 (normal left inverted right x axis y axis) 344mm x 194mm
# "DP-2 DP-6 eDP-1-1 HDMI-0"
MONITORS="${MONITORS[@]}"

if [ "$MONITORS" == "DP-2 DP-6 eDP-1-1 HDMI-0" ]; then
    METAMODE=$(nvidia-settings --query CurrentMetaMode)
    if [ -n "$METAMODE" ]; then
        # to get rid of the 'Attribute .... :: ' name
        #       -e 's/.*\s::\s//'
        # remove any composition pipeline stuff
        #       -e 's/, Force\(Full\)\?CompositionPipeline=\w\+//g' \
        # append desired setting
        #       -e 's/}/, ForceCompositionPipeline=On}/g' \
        METAMODE=$(echo $METAMODE | sed \
            -e 's/.*\s::\s//' \
            -e 's/, Force\(Full\)\?CompositionPipeline=\w\+//g' \
            -e 's/}/, ForceCompositionPipeline=On}/g' \
        ) 
        nvidia-settings -a "CurrentMetaMode=${METAMODE}"
    fi
    # 4 monitor setup
    #       eDP-1-1: laptop display
    #       DP-2: DisplayPort 1.3 over USB 3.1 Gen 2 Type-C
    #       DP-6: Mini DisplayPort
    #       HDMI-0: HDMI
    # see https://wiki.archlinux.org/index.php/NVIDIA/Troubleshooting#Multi-monitor
    xrandr \
        --output DP-0 --off \
        --output DP-1 --off \
        --output DP-2 --mode 1920x1080 --pos 3840x0 --rotate normal --dpi 102 \
        --output DP-3 --off \
        --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal --dpi 102 \
        --output DP-4 --off \
        --output DP-5 --off \
        --output DP-6 --mode 1920x1080 --pos 1920x0 --rotate normal --dpi 102 \
        --output eDP-1-1 --primary --mode 1920x1080 --pos 5760x0 --rotate normal --dpi 141
else
    echo "No recognized configuration."
fi
