#! /bin/sh
#
# vconsole_setup.sh
# Copyright (C) 2021 Mark Wells <mwellsa@gmail.com>
#
# Distributed under terms of the MIT license.
#

KEYMAPSDIR=/usr/local/share/kbd/keymaps

mkdir -vp $KEYMAPSDIR

cp -tvf $KEYMAPSDIR personal.map
cp -tvf /etc vconsole.conf
