#! /bin/sh
#
# launch
# Copyright (C) 2021 Mark Wells <mwellsa@gmail.com>
#
# Distributed under terms of the MIT license.
#

MONITORS=( $(xrandr --listmonitors | rev | cut -d' ' -f1 | rev ) )
MONITORS="${MONITORS[@]}"

external_monitor () {
    local MONITOR=$1
    local DDCCI_BUS=$2
    if [[ $MONITORS == *"$MONITOR"* ]] && [ -n "$(ddcutil getvcp 10 -b $DDCCI_BUS)" ]; then
        source ${HOME}/.config/polybar/launch_external
    fi
}

# launch polybars async
external_monitor DP-2 10 &
external_monitor HDMI-0 11 &
external_monitor DP-6 13 &
