#!/bin/bash

if [ $(id -u) -ne 0 ]; then
    echo "This script should be run as root!" >&2
    exit 1
fi

MODLOADCONF="/etc/modules-load.d/ddcci.conf"
echo "Writing ${MODLOADCONF}"
echo '# Load ddcci at boot' | tee $MODLOADCONF
echo 'ddcci' | tee --append $MODLOADCONF

MODPROBECONF="/etc/modprobe.d/ddcci.conf"
echo "Writing ${MODPROBECONF}"
echo 'options ddcci dyndbg delay=120' | tee $MODPROBECONF
echo 'options ddcci-backlight dyndbg' | tee --append $MODPROBECONF

_USER=$USER
if [ $SUDO_USER ]; then
    _USER=$SUDO_USER
fi

echo ""
if groups $_USER | grep -q video; then
    echo "$_USER is already in group video"
else
    echo "adding $_USER to group video"
    usermod -aG video $_USER
fi
