#!/bin/bash

if [ $(id -u) -ne 0 ]; then
    echo "This script should be run as root!" >&2
    exit 1
fi

if systemctl --quiet is-active sshd.service; then
    systemctl stop sshd.service
fi

if systemctl --quiet is-enabled sshd.service; then
    echo "sshd.service is already enabled"
else
    systemctl enable sshd.service
fi

systemctl start sshd.service

echo "It is recommended to disable tunneled clear text passwords (require ssh keys)"
echo 'Once the ssh-keys are setup set "PasswordAuthentication no" in "/etc/ssh/sshd_config"'

#sed -i -E "s/^#?[[:space:]]?PasswordAuthentication[[:space:]](yes|no)/PasswordAuthentication no/" /etc/ssh/sshd_config
