#!/bin/bash
#
# systemd-resolved is a systemd service that provides network name resolution to
# local applications via a D-Bus interface, the resolve NSS service
# (nss-resolve(8)), and a local DNS stub listener on 127.0.0.53.

main () {
    systemctl enable systemd-resolved.service
    systemctl start systemd-resolved.service
}

while test $# -gt 0; do
    case "$1" in
        -h|--help)
            echo "Enable network name resolution using systemd"
            echo " "
            echo "options:"
            echo "    -f, --force       skip root/sudo check"
            echo " "
            exit 0
            ;;
        -f|--force)
            main
            exit 0
            ;;
        *)
            echo "Unknown option $1"
            exit 1
            ;;
    esac
done

if [ $(id -u) -eq 0 ]; then
    echo "This script should not be run as root!" >&2
    exit 1
else
    main
fi
